'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.81.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class Interfaces
    
    Private interfaceField() As InterfacesInterface
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Interface")>  _
    Public Property [Interface]() As InterfacesInterface()
        Get
            Return Me.interfaceField
        End Get
        Set
            Me.interfaceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class InterfacesInterface
    
    Private interfaceCodeField As UShort
    
    Private accessIDField As String
    
    Private passwordField As String
    
    '''<remarks/>
    Public Property InterfaceCode() As UShort
        Get
            Return Me.interfaceCodeField
        End Get
        Set
            Me.interfaceCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property AccessID() As String
        Get
            Return Me.accessIDField
        End Get
        Set
            Me.accessIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
End Class
